### ISSUE TITLE
undefined method `to_f' for ActiveRecord::VERSION:Module

### ISSUE THREAD

**Issue by eiked** [westonganger/protected_attributes_continued#10]
Hi everyone at protected_attributes_continued

in  protected_attributes_continued/lib/active_record/mass_assignment_security/associations.rb:8:in `block in build_record'

`          the_scope = (ActiveRecord::VERSION.to_f >= 5.2 ? scope_for_create : create_scope)
`

fails with:
`undefined method `to_f' for ActiveRecord::VERSION:Module`
at least with older version of rails. I tried:
- Rails.version => "5.0.6"
- Rails.version => "5.1.6"

You might want to use instead:
`Rails.version.to_f`

**Comment by eiked** [comment]
- Rails.version => "5.2.0"
```
ActiveRecord::VERSION.to_f
NoMethodError: undefined method `to_f' for ActiveRecord::VERSION:Module
```

Maybe this is because I take it from the trunk:
Gemfile:
`gem 'protected_attributes_continued', git:'https://github.com/westonganger/protected_attributes_continued.git'
`

**Comment by westonganger** [comment]
Sorry its supposed to be `ActiveRecord::VERSION::STRING.to_f`. I already looked into this awhile ago... not sure why it wasn't pushed.
