### ISSUE TITLE
Gem not 100% working with Rails 6

### ISSUE THREAD

**Issue by gabceb** [westonganger/protected_attributes_continued#15]
Hi all!

First, thanks for this gem! Im in the process of migrating a Rails 4 project (that used the `protected_attributes` gem) to Rails 6 + this gem but quickly noticed my models would we acting out. Once I remove this gem and all references to `attr_accessible` the models are back to working as usual.

One of the many things I noticed was the inability to save new models (`save!` just returned **true** or `model.persisted?` returning `true` for new, not saved models)

I will probably migrate my project away from `attr_accessible` but wanted to make everyone here aware in case anyone is up for a fix

**Comment by westonganger** [comment]
While it does mostly work with Rails 6, it may need some updates to fully support some of the changes in ActiveRecord. 

I would love to see any PRs, if anyone is willing to help tackle this.

**Comment by madlew** [comment]
btw. I believe you should not jump straight from Rails 4 to 6 but go up version (major) by version

**Comment by westonganger** [comment]
@madlew Im not sure you have looked in this repository before making that comment. 

This gem tested against all versions of Rais 5.x and is actively used in many current Rails 5.x projects. Rails 6 is the next step.

**Comment by madlew** [comment]
@westonganger I'm not sure if you read my comment carefully - I said nothing about this gem but just about the strategy of going from Rails 4 to Rails 6. It seems @gabceb goes straight from 4 to 6, whereas the official guide suggests  https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#the-upgrade-process

by the time @gabceb migrates to 5.0.7.2, then to 5.1.7 and finally to 5.2.4, this gem probably will be ready to support Rails 6.0

**Comment by madlew** [comment]
btw. We're currently in process of getting rid of this gem from our project. Frankly speaking the more versions of Rails it supports, the worse for some projects in long term ..unless they are not under active maintenance, though if someone decides to bump Rails in most cases it means a lot of maintenance work automatically.

If it didn't exist, we'd be forced to migrate to strong params much earlier, which would serve much better for our project. Taking shortcuts in short term does not pay off in longer term.

**Comment by gabceb** [comment]
Your comments aren’t really helpful on this context @madlew but thanks for the advise. I just reached Balmer’s peak one night and migrated to strong params. I also migrated successfully from 4 to 6 so all is well

@westonganger i do appreciate this project and all the time it saved me. You rock 🤟🏻

**Comment by madlew** [comment]
lucky you! one of the key advantages of going version by version is getting really helpful deprecation warnings before the turn into errors but it all strongly depends on a project

btw. if you already migrated to strong params, what do you still need this gem for?

**Comment by westonganger** [comment]
@madlew @gabceb Have you seen my interpretation of a strong_params version of this gem: https://github.com/westonganger/protected_attributes_continued#a-simple-and-similar-strong_params-alternative

**Comment by gabceb** [comment]
@madlew i was just trying to be a good Open Source citizen and report the issue. Hopefully this could help someone like me in the future.

@westonganger i think i went with something like that in the end 👍🏻

**Comment by madlew** [comment]
@westonganger that looks nice indeed! thanks for sharing/inspiration!

**Comment by richkettle** [comment]
To add to this. It appears as though this is also not working with habtm relationships. The accessor for setting the relationship appears to be going undefined.

**Comment by westonganger** [comment]
@richkettle that issue has now been solved by #18

**Comment by westonganger** [comment]
v1.6.0 is released and has added Rails 6 to the test matrix and the fix for #18. 

I am going to close this issue so that any more specific errors about Rails 6 can be raised.
