### ISSUE TITLE
With Rails 7, is it working?

### ISSUE THREAD

**Issue by jean202222222** [westonganger/protected_attributes_continued#28]
Hi
With Rails 7, i install gem protected_attributes_continued (1.8.2)
When i run a rake task, i have the message:
NoMethodError: undefined method `attr_protected' for Autocall:Class
First, what can i check about installation?

**Comment by westonganger** [comment]
Test suite with Rails 7 was passing 3 weeks ago.

Some things to check:

- Does it work outside of Rake tasks?
- Are you running your rake task with `bundle exec`
- Did you add gem to `Gemfile` and bundle install (dont use gem install)
- Do you have any special require flows that might be missing this? Maybe try creating an initializer with `require 'protected_attributes_continued'` inside it

**Comment by jean202222222** [comment]
I add gem to Gemfile and bundle install and now with bundle exec or without, it's ok. I continue my tests. Thank you very much
