### ISSUE TITLE
Controller scope

### ISSUE THREAD

**Issue by TheRusskiy** [westonganger/protected_attributes_continued#5]
This is not an issue, but more of a question / suggestion.

Is it possible to enable strong_parameters for some controllers? And this for others?
Would be very helpful to migrate to new gem one controller at a time

**Comment by westonganger** [comment]
Either the attributes must be `attr_accessible` in the model (protected_attributes) OR you can use `params.require().permit()` in the controller (strong_params). There is nothing to enable/or disable.

**Comment by TheRusskiy** [comment]
@westonganger I guess what I am asking would be too complex. I meant allowing to use parameters via attr_accessible from some controllers but not others.
