### ISSUE TITLE
Rails 5 ActiveRecord #new only accepts 1 argument but you pass 2

### ISSUE THREAD

**Issue by rowanjt** [westonganger/protected_attributes_continued#8]
I get the following error: ArgumentError - wrong number of arguments (given 2, expected 0..1)

https://github.com/westonganger/protected_attributes_continued/blob/b660fcde3e231b1b040f76e8f385f85c8933159d/lib/active_record/mass_assignment_security/persistence.rb#L41

http://api.rubyonrails.org/classes/ActiveRecord/Core.html#method-c-new

**Comment by westonganger** [comment]
Please provide your relevant code snippets and which version of Rails you are using.

**Comment by rowanjt** [comment]
ruby '2.3.1'
gem 'rails', '5.1.4'

For a model in which I have a defined state machine calling "model.create" gives the above error.
I had to do a local monkey patch to fix the issue:

```ruby
module ActiveRecord
  module MassAssignmentSecurity
    module Persistence
      module ClassMethods
        def create(attributes = nil, options = {}, &block)
          if attributes.is_a?(Array)
            attributes.collect { |attr| create(attr, &block) }
          else
            object = new(attributes, &block)
            object.save
            object
          end
        end
      end
    end
  end
end
```

**Comment by scarver2** [comment]
I'm encountering the same issue. Is there an approved solution?
